-- Baseline schema for BrochureDB.
--
-- WHY THIS EXISTS
--   ARCHITECTURE.md §12.1 recorded that several tables, generated columns, and
--   the Storage bucket lived in the live database and NOT in any .sql file in
--   this repo, so a fresh Supabase project could not be provisioned from the
--   code. This file closes that gap: it reproduces every public object the
--   running app depends on, captured on 2026-07-30 from project
--   qpqdbyhfquqfrkrocnnu via pg_catalog / pg_get_functiondef so the definitions
--   are byte-identical to production, not reconstructed from memory.
--
-- HOW IT IS APPLIED
--   Migrations flow through Claude Code via the Supabase MCP, not through the
--   `Deploy Supabase migrations` GitHub workflow (see ARCHITECTURE.md §0/§12.1).
--   This file was applied that way against the live project; the ledger entry
--   records the version and future `supabase db push` will see it as up-to-date.
--
-- IDEMPOTENT THROUGHOUT
--   Every statement is safe to re-run. That matters because (a) applying this
--   against the live project must be a semantic no-op, and (b) a fresh project
--   should be able to run this file plus the seven post-baseline migrations
--   already present in this folder without conflict — the post-baseline files
--   layer changes that this baseline already contains, so on a fresh env they
--   become no-ops via IF NOT EXISTS.
--
-- WHAT IT DELIBERATELY DOES NOT INCLUDE
--   * Data — schema only.
--   * `auth.*`, `storage.*` internals — Supabase provides those.
--   * pg_trgm/vector internal functions — CREATE EXTENSION brings them in.
--   * Storage RLS policies on `storage.objects` for `brochure-pages` — the
--     backend uses the service_role key which bypasses RLS, so no policy was
--     ever needed and none exists in production. Documented here so a future
--     reviewer does not add speculative policies "just to have some."


-- ── Extensions ────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto    WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS vector      WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm     WITH SCHEMA public;


-- ── Tables ────────────────────────────────────────────────────────────────
-- Order matters only where FKs reference an earlier table. Every column
-- default and check constraint is preserved exactly.

CREATE TABLE IF NOT EXISTS public.profiles (
  id         uuid PRIMARY KEY REFERENCES auth.users(id),
  role       text NOT NULL DEFAULT 'viewer' CHECK (role = ANY (ARRAY['admin','manager','viewer'])),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chemicals (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cas_number text UNIQUE,
  name_en    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.companies (
  id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at      timestamptz NOT NULL DEFAULT now(),
  company_name    text NOT NULL,
  contact_number  text UNIQUE,
  email           text UNIQUE,
  company_name_en text,
  website         text,
  website_domain  text,
  extra_details   jsonb
);
COMMENT ON TABLE public.companies IS 'the details of companies';

-- documents is BOTH the extraction work queue AND the dedup ledger. The primary
-- key is content_hash so uploading the same PDF a second time hits ON CONFLICT
-- and returns the existing document rather than paying to re-extract it.
CREATE TABLE IF NOT EXISTS public.documents (
  content_hash     text PRIMARY KEY,
  filename         text,
  company_id       bigint REFERENCES public.companies(id),
  product_count    integer NOT NULL DEFAULT 0,
  uploaded_by      uuid REFERENCES auth.users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  listing_ids      uuid[] NOT NULL DEFAULT '{}'::uuid[],
  id               uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  status           text NOT NULL DEFAULT 'pending' CHECK (status = ANY (ARRAY[
                     'staged','pending','splitting','split','claimed',
                     'extracting','paused','done','failed','cancelled'])),
  running_context  jsonb,
  page_count       integer,
  claimed_by       text,
  claimed_at       timestamptz,
  cancel_requested boolean NOT NULL DEFAULT false,
  error            text,
  fatal            boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.pages (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id     uuid NOT NULL REFERENCES public.documents(id),
  page_number     integer NOT NULL,
  image_path      text,
  status          text NOT NULL DEFAULT 'pending' CHECK (status = ANY (ARRAY[
                    'pending','claimed','extracting','done','failed','dead'])),
  attempts        integer NOT NULL DEFAULT 0,
  claimed_at      timestamptz,
  markdown_output text,
  raw_json        jsonb,
  error_message   text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_id, page_number)
);

CREATE TABLE IF NOT EXISTS public.listings (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chemical_id     uuid REFERENCES public.chemicals(id),
  name_raw        text NOT NULL,
  name_en         text NOT NULL,
  cas_number      text,
  cas_number_raw  text,
  price           numeric,
  currency        text,
  purity          text,
  needs_review    boolean NOT NULL DEFAULT false,
  review_reason   text,
  uploaded_by     uuid REFERENCES auth.users(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  company_id      bigint REFERENCES public.companies(id),
  dedup_key       text,
  details         jsonb,
  characteristics jsonb,      -- populated by page_extract but NOT read anywhere;
                              -- worker writes model output to `details` instead
                              -- (worker._build_details). Kept for schema parity.
  company_website text,
  price_usd       numeric,
  document_id     uuid REFERENCES public.documents(id),
  source_page_id  uuid REFERENCES public.pages(id)
);

CREATE TABLE IF NOT EXISTS public.exchange_rates (
  code         text PRIMARY KEY,
  rate_per_usd numeric NOT NULL,
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  actor      uuid,
  action     text NOT NULL,
  details    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chemical_embeddings (
  chemical_id uuid PRIMARY KEY REFERENCES public.chemicals(id),
  embedding   extensions.vector NOT NULL,
  source_text text NOT NULL,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.substitution_notes (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  from_chemical_id uuid NOT NULL REFERENCES public.chemicals(id),
  to_chemical_id   uuid REFERENCES public.chemicals(id),
  to_name          text NOT NULL,
  verdict          text NOT NULL DEFAULT 'works' CHECK (verdict = ANY (ARRAY['works','conditional','avoid'])),
  context          text NOT NULL,
  author_id        uuid REFERENCES auth.users(id),
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.regulatory_notes (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chemical_id    uuid NOT NULL REFERENCES public.chemicals(id),
  jurisdiction   text NOT NULL,
  status         text NOT NULL CHECK (status = ANY (ARRAY['banned','restricted','phase_out','permitted','unclear'])),
  effective_date date,
  note           text NOT NULL,
  source_url     text,
  author_id      uuid REFERENCES auth.users(id),
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_settings (
  key         text PRIMARY KEY,
  value       text NOT NULL DEFAULT '',
  is_secret   boolean NOT NULL DEFAULT false,
  category    text NOT NULL DEFAULT 'general',
  label       text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  updated_at  timestamptz NOT NULL DEFAULT now(),
  updated_by  uuid REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.settings_audit (
  id          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  setting_key text NOT NULL,
  old_value   text,
  new_value   text,
  changed_by  uuid REFERENCES auth.users(id),
  changed_at  timestamptz NOT NULL DEFAULT now()
);


-- ── Functions ─────────────────────────────────────────────────────────────

-- Ensures every new auth user gets a profile row with the default 'viewer'
-- role. SECURITY DEFINER because auth.users triggers run as the auth owner.
CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, role)
  values (new.id, 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$function$;

-- Belt-and-braces: any table created in public gets RLS enabled automatically,
-- so a forgotten `alter table … enable row level security` cannot silently
-- ship an open table. Runs on ddl_command_end for CREATE TABLE only.
CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

-- Semantic search over chemical embeddings. Takes the query embedding as text
-- so the PostgREST RPC surface can be called without vector type knowledge.
CREATE OR REPLACE FUNCTION public.match_chemicals(
  query_embedding text,
  match_count integer DEFAULT 8,
  exclude_id uuid DEFAULT NULL::uuid,
  min_similarity real DEFAULT 0.0
)
  RETURNS TABLE(chemical_id uuid, name_en text, cas_number text, similarity real)
  LANGUAGE sql
  STABLE
  SET search_path TO 'public', 'extensions'
AS $function$
  select
    ce.chemical_id,
    c.name_en,
    c.cas_number,
    (1 - (ce.embedding <=> query_embedding::extensions.vector))::real as similarity
  from public.chemical_embeddings ce
  join public.chemicals c on c.id = ce.chemical_id
  where (exclude_id is null or ce.chemical_id <> exclude_id)
    and (1 - (ce.embedding <=> query_embedding::extensions.vector)) >= min_similarity
  order by ce.embedding <=> query_embedding::extensions.vector
  limit match_count;
$function$;

-- Worker claim loop. Longest-job-first so a 200-page catalog starts before a
-- 3-page flyer; FOR UPDATE SKIP LOCKED so N workers never collide; claims from
-- both 'pending' and 'split' so a worker that died after splitting can resume.
CREATE OR REPLACE FUNCTION public.claim_next_document(p_worker_id text)
  RETURNS documents
  LANGUAGE plpgsql
AS $function$
declare
  claimed public.documents;
begin
  update public.documents d
  set status = 'extracting', claimed_by = p_worker_id, claimed_at = now()
  where d.id = (
    select id from public.documents
    where status in ('pending', 'split')
      and coalesce(cancel_requested, false) = false
    order by page_count desc nulls last
    limit 1
    for update skip locked
  )
  returning d.* into claimed;
  return claimed;
end;
$function$;

-- PostgREST computed fields — NOT columns. They surface as virtual columns to
-- REST clients but are functions taking the row type. Auditing for them as
-- columns via information_schema.columns reports them missing when they exist.

-- Broad match surface: names in both scripts, CAS, every detail value, and
-- the supplier's name. STABLE (not IMMUTABLE) because it reads companies.
CREATE OR REPLACE FUNCTION public.search_text(l listings)
  RETURNS text
  LANGUAGE sql
  STABLE
AS $function$
  select concat_ws(' ',
    l.name_raw,
    l.name_en,
    l.cas_number,
    l.details::text,
    (select concat_ws(' ', c.company_name, c.company_name_en)
       from public.companies c
      where c.id = l.company_id)
  )
$function$;

-- Details-only surface, so a query can target printed attributes without
-- name/CAS/supplier text producing false positives.
CREATE OR REPLACE FUNCTION public.details_text(listings)
  RETURNS text
  LANGUAGE sql
  IMMUTABLE
AS $function$
  select coalesce($1.details::text, '')
$function$;


-- ── Triggers ──────────────────────────────────────────────────────────────

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

DROP EVENT TRIGGER IF EXISTS ensure_rls;
CREATE EVENT TRIGGER ensure_rls
  ON ddl_command_end
  EXECUTE FUNCTION public.rls_auto_enable();


-- ── Indexes ───────────────────────────────────────────────────────────────

CREATE INDEX        IF NOT EXISTS audit_log_created_at_idx      ON public.audit_log           USING btree (created_at DESC);
CREATE INDEX        IF NOT EXISTS idx_chemical_embeddings_hnsw  ON public.chemical_embeddings USING hnsw (embedding extensions.vector_cosine_ops);
CREATE INDEX        IF NOT EXISTS idx_chemicals_name_en         ON public.chemicals           USING btree (name_en);
CREATE INDEX        IF NOT EXISTS idx_companies_name_trgm       ON public.companies           USING gin (company_name gin_trgm_ops);
CREATE INDEX        IF NOT EXISTS idx_documents_status          ON public.documents           USING btree (status);
CREATE INDEX        IF NOT EXISTS idx_listings_cas_number       ON public.listings            USING btree (cas_number);
CREATE INDEX        IF NOT EXISTS idx_listings_chemical_id      ON public.listings            USING btree (chemical_id);
CREATE INDEX        IF NOT EXISTS idx_listings_details          ON public.listings            USING gin (details);
CREATE INDEX        IF NOT EXISTS idx_listings_document_id      ON public.listings            USING btree (document_id);
CREATE INDEX        IF NOT EXISTS idx_listings_name_en          ON public.listings            USING btree (name_en);
CREATE INDEX        IF NOT EXISTS idx_listings_price            ON public.listings            USING btree (price);
CREATE INDEX        IF NOT EXISTS idx_listings_price_usd        ON public.listings            USING btree (price_usd);
CREATE INDEX        IF NOT EXISTS idx_listings_source_page_id   ON public.listings            USING btree (source_page_id);
CREATE INDEX        IF NOT EXISTS idx_pages_document_id_status  ON public.pages               USING btree (document_id, status);
CREATE INDEX        IF NOT EXISTS idx_pages_status              ON public.pages               USING btree (status);
CREATE INDEX        IF NOT EXISTS idx_regulatory_notes_chemical ON public.regulatory_notes    USING btree (chemical_id);
CREATE INDEX        IF NOT EXISTS idx_substitution_notes_from   ON public.substitution_notes  USING btree (from_chemical_id);
CREATE INDEX        IF NOT EXISTS idx_substitution_notes_to     ON public.substitution_notes  USING btree (to_chemical_id);
CREATE UNIQUE INDEX IF NOT EXISTS listings_dedup_key_uidx       ON public.listings            USING btree (dedup_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_companies_website_domain   ON public.companies           USING btree (website_domain) WHERE (website_domain IS NOT NULL);


-- ── RLS: enable everywhere ────────────────────────────────────────────────
-- The ensure_rls event trigger already does this on CREATE TABLE, but declaring
-- it explicitly makes reprovisioning survive an event trigger being disabled.

ALTER TABLE public.profiles            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chemicals           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pages               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exchange_rates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chemical_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.substitution_notes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.regulatory_notes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings_audit      ENABLE ROW LEVEL SECURITY;


-- ── RLS policies ──────────────────────────────────────────────────────────
-- The backend uses the service_role key which bypasses RLS entirely — these
-- policies exist so the frontend can read the catalog directly with an
-- authenticated anon-key session. Every write path goes through the backend.
-- DROP-then-CREATE for idempotency (Postgres has no CREATE POLICY IF NOT EXISTS).

DROP POLICY IF EXISTS "read own profile"                    ON public.profiles;
CREATE POLICY "read own profile"                            ON public.profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "authenticated read chemicals"        ON public.chemicals;
CREATE POLICY "authenticated read chemicals"                ON public.chemicals
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "authenticated read listings"         ON public.listings;
CREATE POLICY "authenticated read listings"                 ON public.listings
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "authenticated read documents"        ON public.documents;
CREATE POLICY "authenticated read documents"                ON public.documents
  FOR SELECT TO authenticated USING (true);

-- Documents/pages have an EXTRA admin-manager read policy on top of the
-- authenticated one because some admin queries widened the row-level filter
-- beyond what the base policy already implies (SELECT true). Kept for parity
-- with production; they are additive, not restrictive.
DROP POLICY IF EXISTS "admin_manager read documents"        ON public.documents;
CREATE POLICY "admin_manager read documents"                ON public.documents
  FOR SELECT TO authenticated USING (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['admin','manager'])
  ));

DROP POLICY IF EXISTS "admin_manager read pages"            ON public.pages;
CREATE POLICY "admin_manager read pages"                    ON public.pages
  FOR SELECT TO authenticated USING (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['admin','manager'])
  ));

DROP POLICY IF EXISTS "authenticated read chemical_embeddings" ON public.chemical_embeddings;
CREATE POLICY "authenticated read chemical_embeddings"         ON public.chemical_embeddings
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "authenticated read substitution_notes"  ON public.substitution_notes;
CREATE POLICY "authenticated read substitution_notes"          ON public.substitution_notes
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "authenticated read regulatory_notes"    ON public.regulatory_notes;
CREATE POLICY "authenticated read regulatory_notes"            ON public.regulatory_notes
  FOR SELECT TO authenticated USING (true);


-- ── Storage: the brochure-pages bucket ────────────────────────────────────
-- Private bucket; the backend uploads and reads with the service_role key,
-- which bypasses RLS. No storage.objects policies are needed and none exist in
-- production. If a future feature ever needs direct browser access to a page
-- image, add policies here — do not make the bucket public.

INSERT INTO storage.buckets (id, name, public)
VALUES ('brochure-pages', 'brochure-pages', false)
ON CONFLICT (id) DO NOTHING;


-- ── Function grants ───────────────────────────────────────────────────────
-- service_role only. The browser never invokes these RPCs directly; the
-- backend does, holding the service key. Explicit REVOKE first so re-running
-- cannot silently widen access.

REVOKE ALL ON FUNCTION public.claim_next_document(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.search_text(listings)     FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.details_text(listings)    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.match_chemicals(text, integer, uuid, real)
                                                        FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.claim_next_document(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.search_text(listings)     TO service_role;
GRANT EXECUTE ON FUNCTION public.details_text(listings)    TO service_role;
GRANT EXECUTE ON FUNCTION public.match_chemicals(text, integer, uuid, real)
                                                           TO service_role;
